cheese_dict = {'red leicester': 'I\'m, a-fraid we\'re fresh out of Red Leicester, Sir.',
               'tilsit': 'I\'m afraid we never have that at the end of the week, Sir, we get it fresh on Monday.',
               'caerphilly': 'Ah! It\'s beeeen on order, Sir, for two weeks. Was expecting it this morning.',
               'bel paese': 'Sorry, Sir.',
               'red windsor': 'Normally, Sir, yes. Today the van broke down.',
               'stilton': 'Sorry.',
               'gruyere': 'No.',
               'emmental': 'No.',
               'norwegian jarlsberger': 'No.',
               'liptauer': 'No.',
               'lancashire': 'No.',
               'white stilton': 'No.',
               'danish blue': 'No.',
               'double gloucester': 'No.',
               'cheshire': 'No.',
               'dorset blue vinney': 'No.',
               'brie': 'No.',
               'roquefort': 'No.',
               'pont-l\'eveque': 'No.',
               'port salut': 'No.',
               'savoyard': 'No.',
               'saint-paulin': 'No.',
               'carre-de-l\'est': 'No.',
               'boursin': 'No.',
               'bresse bleu': 'No.',
               'perle de champagne': 'No.',
               'camenbert': 'Ah! We have Camembert, yessir. It\'s ah... it\'s a bit runny. Oooooh..! The cat\'s eaten it.',
               'gouda': 'No.',
               'edam': 'No.',
               'caithness': 'No.',
               'smoked austrian': 'No.',
               'japanese sage darby': 'No.',
               'wensleydale': 'Yes? Oh! I thought you were talking to me, Sir. Mister Wensleydale, that\'s my name.',
               'greek feta': 'Uh, not as such.',
               'gorgonzola': 'No.',
               'parmesan': 'No.',
               'mozzarella': 'No.',
               'pippo creme': 'No.',
               'danish fimboe': 'No.',
               'czech sheep\'s milk': 'No.',
               'cheddar': 'Well, we don\'t get much call for it around here, Sir.',
               'ilchester': 'I\'ll have a look, sir.. nnnnnnnnnnnnnnnno.',
               'limburger': 'No.'}
print("In a nutshell. And I thought to myself, 'a little fermented curd will do the trick', so, I curtailed my Walpoling activites, sallied forth, and infiltrated your place of purveyance to negotiate the vending of some cheesy comestibles!\nCome again?\nI want to buy some cheese!")
s = input('Oh, certainly, Sir. What would you like? ').lower()
try:
    print(cheese_dict[s])
except KeyError:
    print('Pardon?')
